#!/bin/bash

echo '1. List all available subscriptions'
echo '2. Select subscription'
echo '3. Use personal subscription'
echo '4. Show currently active subscription'

read -p 'Selection: ' VARCHOICE


if [[ $VARCHOICE -eq 1 ]]
then
    az account list -o table
elif [[ $VARCHOICE -eq 2 ]]
then
    read -p 'Please provide subscription ID: ' SUBID
    az account set --subscription "$SUBID"
    echo "$SUBID"
elif [[ $VARCHOICE -eq 3 ]]
then
    if [[ -z $PERSONAL_SUB ]]
    then
        echo 'Please set the PERSONAL_SUB environmental variable to your Subscription ID'
        echo 'example: '
        echo 'export PERSONAL_SUB="SUB_ID_GOES_HERE"'
        exit 2
    fi
    az account set --subscription $PERSONAL_SUB
    echo $PERSONAL_SUB
elif [[ $VARCHOICE -eq 4 ]]
then
    az account show
else
    echo 'Incorrect input'
fi
